[theme]
primaryColor="#228B22"
backgroundColor="#000000"  # Black background
secondaryBackgroundColor="#191919"  # Darker grey for secondary background
textColor="#FFFFFF"  # White text color
font="sans serif"